### ISSUE TITLE
Add "bib" records (Book records)

### ISSUE THREAD

**Issue by salamander2** [salamander2/Library-demo#10]
I have about 500 records that can be imported into the Bib table.
There are two formats, one from UWO library and one from our school library. You can do whatever you want.
Either way you'll have to manipulate the data a bit before you import it. The data has to match the fields in the Bib table.

** The call_number was set to be only 15 chars long in the 'bib' table.  First we need to change that to be about ~~30~~ 50 chars long.

**Comment by mangdani282** [comment]
I changed the length of call_number to 50, but I was confused about the csv files. The LCSS file doesn't have a publishing date or subjects, and the UWO file doesn't have Call Number or ISBN. In my opinion the Call Number and ISBN are more important so I'm leaning towards the LCSS file. If I try to import the LCSS file should I just leave the publishing date and subjects blank?

**Comment by salamander2** [comment]
Yes, we need ISBN and Call Number. But also the PUB DATE. "Subject" can just be left blank.
So maybe create random pub dates when you load the records.
Or perhaps grab the pubdate column from UWO and just stick it onto the LCSS one.  This would be easiest to do in Excel.

** I'll try and do this this evening.

**Comment by salamander2** [comment]
@Be4nis 

1. I've added pubdates to all the books (copying the ones from UWO and then just pasting a new column).
2. Some of the authors' names have issues. The names often seem to have dates as well (when the author was born). It would be nice for the program that loads them in to delete them. The author is always in " ", as "lastname, firstname".  But sometimes there's a second comma with dates. Everything from the second comma onwards can be deleted.
3. I don't think that the ISBN field is big enough for the ISBNs.  Can you change the BIB table to make ISBN "unsigned bigint" ?
4. I think that's all.  Thanks.

**Comment by Be4nis** [comment]
Yes, I will do it on Friday (during the club) and this weekend.

**Comment by salamander2** [comment]
How are things going?

**Comment by Be4nis** [comment]
I believe Daniel has fixed the table, I am confused about the second task. Do we create a webpage where users enter the data and then use an algorithm written in PHP to find and remove the date?

![image](https://user-images.githubusercontent.com/101023105/223907143-8f1e5f1b-f90b-46ca-8f5a-c2a2534aed04.png)

**Comment by salamander2** [comment]
Hi,
No, we just write a PHP program to load the data or use an IMPORT command (from the command line).We only have to do this once. I think that you or someone has the book data already setup.
I'll try and find the import syntax (it's faster as it's just a single line that you run, no programming needed).

    On Wednesday, March 8, 2023 at 10:16:37 PM EST, Brian Zhang ***@***.***> wrote:  
 
 


I believe Daniel has fixed the table, I am confused about the second task. Do we create a webpage where users enter the data and then use an algorithm written in PHP to find and remove the date?

**Comment by mangdani282** [comment]
I think I've figured out the code, although there's probably a syntax error somewhere lol
```
LOAD DATA INFILE '/home/_share/LCSS_Books.csv'     # I used the directory for the file but it might have to be changed depending on how the server was set up
INTO TABLE bib
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'     # OPTIONALLY is important so that it removes quotation marks around the strings but not the ints
LINES TERMINATED BY '\n'
IGNORE 2 ROWS     # The first row states what each column is, and I already imported the second row to set the id as '30748xxxxx'
(title,@author,call_number,ISBN,pub_date)     # Have to specify the order of columns as they don't match. Also, I think the @ behind author means it turns into a variable that I used below? (get rid of dates in author column)
SET author = SUBSTRING_INDEX(@author, ',', 2);     # Gets a substring of author that ends when two ',' have occurred
```
However, it says that I don't have the permission/access to do this. I think it might have something to do with the file directory? The program has to find the file and I'm not sure where the file is relative to the server.

**Comment by salamander2** [comment]
I'm not sure if LCSS_Books.csv is in the correct format. Everyone can read it. You would have to make a copy of it into your own home folder in order to edit it.

What is the actual error message?

And I don't know about @author.

**Comment by salamander2** [comment]
**DONE! We loaded in 862 books.**

I have to log in to mysql as "root" and type this: SET GLOBAL local_infile=1;

`
mysql -u webdev2 --local-infile -Be "use libraryDB; LOAD DATA LOCAL INFILE 'LCSS_Books2.csv' REPLACE INTO TABLE bib FIELDS TERMINATED BY ',' ENCLOSED BY '\"' IGNORE 2 LINES (title, author, call_number, ISBN, pub_date);"`

There are 63 books with no authors (where the author is an empty string). These should be deleted.
