### ISSUE TITLE
Download Font-Awesome

### ISSUE THREAD

**Issue by salamander2** [salamander2/Library-demo#11]
I'd like to be able to use font-awesome icons (in addition to Bootstrap).

It's more than just copying one file, there's a whole folder that needs to be copied. 

It's not important, but it would be nice.  Someone could do this in their public_html folder and then when working, I can copy it to /var/www/html (the main location for HTML and CSS files).

**Comment by malekhammoud** [comment]
[Font-awesome](https://webdev.iquark.ca/~mhammoud/font_awesome.html) is ready to use and copied over at any time.

**Comment by salamander2** [comment]
Okay, that is truly amazing!  Thanks so much.
Nice webpage.
