### ISSUE TITLE
Add "createDate" field to tables

### ISSUE THREAD

**Issue by salamander2** [salamander2/Library-demo#17]
Somehow I forgot to specify that we need "createDate" in almost all tables.  This needs fixing now.  If we load all of the Bib records or create library card records, we'll just have to delete the table and then recreate it properly and then reload all the data.

This can be easily done in mySQL (as opposed to using phpmyadmin - which doesn't teach you how to do it)

1. Take the createDate field from the patron table and **add it to users table.**
What I mean is that the patron table is the one that has been created correctly. Get the line that made the createDate from this table (see https://github.com/salamander2/Library-demo/blob/master/docs/SQL_Tables.md )
2. **Add it to the library card table.**
3. For consistency, change the name of the field (column)  "time_stamp" in BIB to "createDate"

The "status" table does not need a create date, since the statuses are basically fixed from the start and don't get added or changed.

**Comment by salamander2** [comment]
I've had to fix the users table already.
LibraryCard and Bib still need fixing.

**Comment by mangdani282** [comment]
That should all be done.

**Comment by salamander2** [comment]
Thanks.
