### ISSUE TITLE
Create Holdings Table

### ISSUE THREAD

**Issue by salamander2** [salamander2/Library-demo#18]
see description in documentation: https://github.com/salamander2/Library-demo/blob/master/docs/DataOrg.md

Ask Mr. Harwood if anything is unclear.

**Comment by mangdani282** [comment]
It should be done, but I feel like I forgot to do something. Let me know if you need me to edit it.

**Comment by salamander2** [comment]
I think it's fine. I looked at the links via phpmyadmin and they seem okay.
![image](https://user-images.githubusercontent.com/2030680/229323928-5b0f9b9a-aac6-4aa6-a8b3-ce03c581bcb2.png)

**Comment by salamander2** [comment]
I'm thinking about what might be missing (see Discord #general)

**Comment by salamander2** [comment]
Other fields for previous patron and checkin/out date have been added.
