### ISSUE TITLE
Write program to add holdings records

### ISSUE THREAD

**Issue by salamander2** [salamander2/Library-demo#20]
We need to write a PHP program to add Holdings records to Bib records.

`SELECT id FROM bib;`

go through each Bib ID and create a holdings record. 

Test it: I think that the barcode will be autogenerated. You do not have to add it in.

About 25% of Bib records should have two holdings (ie. 2 copies of the book)
and 10% should have 3 copies (3 holdings records).

**Comment by malekhammoud** [comment]
This is done.
Code available in my home directory.
