### ISSUE TITLE
get Patron data

### ISSUE THREAD

**Issue by salamander2** [salamander2/Library-demo#4]
* setup database along with Patron table
* get fake Patron data (about 200 records)
* * let's make 80% of the patrons live in London
* import data

**Comment by salamander2** [comment]
Patron fields:



```
+------------+--------------+------+-----+-------------------+-------------------+
| Field      | Type         | Null | Key | Default           | Extra             |
+------------+--------------+------+-----+-------------------+-------------------+
| id         | int unsigned | NO   | PRI | NULL              | auto_increment    |
| firstname  | varchar(30)  | NO   |     | NULL              |                   |
| lastname   | varchar(30)  | NO   |     | NULL              |                   |
| address    | varchar(255) | NO   |     | NULL              |                   |
| city       | varchar(100) | NO   |     | NULL              |                   |
| prov       | varchar(2)   | NO   |     | NULL              |                   |
| postalCode | varchar(6)   | NO   |     | NULL              |                   |
| phone      | varchar(20)  | YES  |     | NULL              |                   |
| email      | varchar(50)  | YES  |     | NULL              |                   |
| birthdate  | date         | NO   |     | NULL              |                   |
| createDate | timestamp    | NO   |     | CURRENT_TIMESTAMP | DEFAULT_GENERATED |
+------------+--------------+------+-----+-------------------+-------------------+

```

**Comment by malekhammoud** [comment]
I created this csv text containing around 200 fake records. The first 40 live outside London.
Now it needs to be inserted into the patron table, probably by using the "LOAD DATA INFILE" command.

[Fake Patron Data.csv](https://github.com/salamander2/Library-demo/files/10823670/Fake.Patron.Data.csv)

**Comment by salamander2** [comment]
@mhammoud-os  That is awesome. You can load it in if you want .. wait. I need to backup the SQL first.

** You need to remove the first and last columns. ID is autogenerated.  createDate is also autogenerated.

**Comment by malekhammoud** [comment]
I tried many different commands to get the patron data into the MySQL table however I keep getting permission denied errors like: 'ERROR 1045 (28000): Access denied' I even tried changing the permissions but I got the same errors.

Instead I created this PHP code to loop through the CVS text and add the values to the MySQL tables manually. It can be found at /home/mhammoud/inserting_data_file.php

<?php`
require_once('common.php');
$db = connectToDB();
$data_file = fopen("patron_data.csv", "r");
while(($data = fgetcsv($data_file,1000,',')) !== FALSE){
        $row = array();
        for($i = 0; $i <count($data); $i++) {
                array_push($row,"$data[$i]");
        }
        print_r($row);
        runSimpleQuery($db,"INSERT INTO patrons (firstname,lastname, address,city, prov, postalCode, phone,email,birthdate) VALUES ('$row[0]', '$row[1]', '$row[2]', '$row[3]', '$row[4]', '$row[5]','$row[6]','$row[7]','$row[8]');");
        echo "\n";
}
?>`
