### ISSUE TITLE
Create Bib table

### ISSUE THREAD

**Issue by salamander2** [salamander2/Library-demo#5]
Brian, let me know when you're done. 
I've added some more stuff to the documentation here.

**Comment by Be4nis** [comment]
I finished making the bib table on last Friday, should I make the user table, librarycard table, holdings table and status table?

Also, is PHPmyAdmin working?

**Comment by salamander2** [comment]
PhpMyAdmin is working. I can't post passwords here :(

NOT the user table. I'll make that.

Holdings: I need to think about the primary key which will be the barcode. 
If we make it unsigned int, then it can be up to 4,294,967,295.
So book barcodes will start with "3" and then the library code. Let's make the code 4 digits: 0748
The remaining 5 digits will be the books. Hmm... that means we can only have 99,999 books. That's probably enough for our purposes.

I'm not sure how to generate this sort of code automatically. If you figure it out, let me know.  Perhaps a formula could be used? Maybe we have a standard sequential primary key (up to 99,999) and the barcode gets created from that.

We'll make patron barcodes (ie library cards) the same, but they will start with a 2. They will be the primary key for the libraryCard table.

The status table is really easy. It would be a nice thing for someone else to try.

Do you know how to make foreign keys? We need those to make the other tables.

**Comment by salamander2** [comment]
@Be4nis   I'm closing this, but read the comment above.
