### ISSUE TITLE
Create page to  Add a Patron

### ISSUE THREAD

**Issue by salamander2** [salamander2/Library-demo#7]

**Comment by salamander2** [comment]
How are things going?
You got a lot done, and then I added some comments to help a bit (on Discord).

**Comment by malekhammoud** [comment]
Status: Almost done

Thank you for your comments. I was a bit busy this past week and couldn't get lots done. However I am almost done with this page now, working on the finishing touches.

**Comment by Be4nis** [comment]
So here is what I want the page to look like:
https://webdev.iquark.ca/~bzhang/addPat.php 

However this is only in HTML and CSS, Malek wrote all the HTML code within PHP and I still have to figure out how to work around that.

**Comment by malekhammoud** [comment]
The [page](https://webdev.iquark.ca/~mhammoud/Library-demo/addPatron.php) finally complete!

I will just have to move the PHP to the start of the document (for convention).
