### ISSUE TITLE
Create Status table.

### ISSUE THREAD

**Issue by salamander2** [salamander2/Library-demo#9]
The "status" table is really simple. It just has two string entries (ie varchar).  See docs/DataOrg.md

Brian and Malek have already been doing stuff with MySQL so if someone else wants to try this, then go ahead. 

Once it's done, update this.

**Comment by salamander2** [comment]
Once the table is made, we can also practice using SQL to create the entries. (Yes, it can be done via phpMyAdmin, but you don't learn much SQL that way).

There is an "enum" data type, but we can always switch it to that later.

status

code | description
------- |---
IN | In
OUT | Out
LOST | Lost
DAMAGED |Damaged (is in library)
DISCARD | To be discarded
REPAIR | Is being repaired
CR | Claimed Returned

**Comment by mangdani282** [comment]
I've made the table, let me know if there are any issues.

**Comment by salamander2** [comment]
@mangdani282  Can you delete the table and create it again?

These changes should be made:
1. make code only 20 characters max, not 255
2. both code and description are required.

The data that you've added looks good.

Thanks.

**Comment by salamander2** [comment]
Current table:

```
> describe status;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| code        | varchar(255) | YES  |     | NULL    |       |
| description | varchar(255) | YES  |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
```

**Comment by mangdani282** [comment]
I've added the changes, however the description for damaged is longer than 20 characters. For now I set the description length to 30, but I can shorten the description if needed.

**Comment by salamander2** [comment]
Great. Note that I said only shorten "code", not description. 

I've updated the table now.

```
> describe status;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| code        | varchar(20)  | NO   | PRI | NULL    |       |
| description | varchar(255) | YES  |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
```

**Comment by salamander2** [comment]
Oh crap. Now description is NULL.

`ALTER TABLE status MODIFY description varchar(255) NOT NULL;`

` ALTER TABLE status ADD PRIMARY KEY (code);`

**Comment by salamander2** [comment]
```
mysql> describe status;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| code        | varchar(20)  | NO   | PRI | NULL    |       |
| description | varchar(255) | NO   |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
2 rows in set (0.00 sec)
```
